name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --all-features
    - name: Run tests
      run: cargo test --all-features
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings
    - name: Doc
      run: cargo doc --all-features --no-deps